services:
  - type: web
    name: carbonwallet
    env: node
    buildCommand: ./build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:WY2OfhYp+4/COu9opwC4zUK7010tT9J5010qrLvoAxs=
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.office365.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: hello@carbon2030.ai
      - key: MAIL_PASSWORD
        value: Carbon999@
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: hello@carbon2030.ai
      - key: MAIL_FROM_NAME
        value: Carbon AI
