[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci --prefer-offline --no-audit',
    'npm run build'
]

[phases.build]
cmds = [
    'mkdir -p storage/framework/{sessions,views,cache}',
    'mkdir -p storage/logs',
    'mkdir -p bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache',
    'touch database/database.sqlite || true',
    'chmod 664 database/database.sqlite || true',
    'php artisan storage:link || true',
    'php artisan migrate --force --no-interaction || true'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
