[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'mkdir -p storage/framework/{sessions,views,cache}',
    'mkdir -p storage/logs',
    'mkdir -p bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache',
    'touch database/database.sqlite || true',
    'php artisan storage:link || true',
    'php artisan migrate --force --no-interaction || true',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'

