[build]
builder = "NIXPACKS"
buildCommand = "composer install --optimize-autoloader --no-scripts --no-interaction && npm install && npm run build"

[start]
command = "php artisan serve --host=0.0.0.0 --port=${PORT}"
